kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
data:
  # Configuration values can be set as key-value properties
  database: mongodb
  database_uri: mongodb://localhost:27017
  
  # Or set as complete file contents (even JSON!)
  keys: | 
    {
      "firstName": "John",
      "lastName": "Doe",
      "isAlive": true
      "age": 38
    }
---
kind: Pod 
apiVersion: v1 
metadata:
  name: pod-env-var 
spec:
  containers:
  - name: simple-test
    image: stefanwalther/docker-test
    envFrom:
        - configMapRef:
            name: example-configmap
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    configMap:
        name: example-configmap 