apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:  
  database: mongodb
  database_uri: mongodb://localhost:27017
  keys: | 
    {
      "firstName": "John",
      "lastName": "Doe",
      "isAlive": true
      "age": 39
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: configmaptestapp
        image: stefanwalther/docker-test
        envFrom:
        - configMapRef:
            name: test-config
        volumeMounts:
        - mountPath: /config
          name: data-volume
        ports:
        - containerPort: 80
      volumes:
        - name: data-volume
          configMap:
            name: test-config