---
apiVersion: v1
kind: Namespace
metadata:
  name: unipr-soi

---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: unipr-soi
spec:
  containers:
  - name: simple-test
    image: stefanwalther/docker-test
    ports:
    - containerPort: 3000
