---
apiVersion: v1
kind: Namespace
metadata:
  name: unipr-soi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: unipr-soi
spec:  
  limits:
  - max:
      memory: 0.5Gi
    min:
      memory: 100Mi
    default:
      memory: 200Mi
    type: Container

---
apiVersion: v1
kind: Pod
metadata:
  name: simple-test-pod  
spec:
  containers:
  - name: simple-test
    image: stefanwalther/docker-test
    ports:
    - containerPort: 3000

