---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    layer: fe
    env: prod    
spec:
  containers:
  - name: simple-test
    image: stefanwalther/docker-test 
    ports:
    - containerPort: 8080



---
apiVersion: v1
kind: Pod
metadata:
  name: database  
  labels:
    layer: be
    env: prod      
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
      - containerPort: 3306
          