apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: client
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: simple-test
        image: stefanwalther/docker-test
