---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  ports:
  - port: 8081
    targetPort: 3000
  selector:
    app: service 
---
apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    app: service    
spec:
  containers:
  - name: simple-test
    image: stefanwalther/docker-test 
    ports:
    - containerPort: 3000