apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: simple-test
    image: stefanwalther/docker-test
    ports:
    - containerPort: 3000
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on node host
      path: /shared
      # this field is optional
      type: Directory